version: '2'
services:
  mysql:
    image: ashanperera/getlinks_test
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-integration-tests
    links:
      - mysql
    depends_on:
      - mysql
    command: ./docker-wait.sh npm start
    environment:
      - NODE_ENV=test
      - PORT=3000
      - MYSQL_CONNECTION=mysql://root:@mysql/getlinks_test
      - JWT_KEY=SUPERSECRETKEY712
      - DEBUG=getlinks-test

